name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  GOPATH: /tmp/

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install gcc-arm-linux-gnueabihf 
      run: sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

    - name: Build-amd64
      run: KUBE_BUILD_PLATFORMS=linux/amd64 make WHAT=cmd/kubelet GOFLAGS=-v 

    - name: Build-arm
      run: KUBE_BUILD_PLATFORMS=linux/arm make WHAT=cmd/kubelet GOFLAGS=-v

